fail_fast: true
default_stages: [commit]
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        name: isort (python)
      - id: isort
        name: isort (cython)
        types: [cython]
      - id: isort
        name: isort (pyi)
        types: [pyi]
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: local
    hooks:
      - id: djangotest
        name: Django Test
        language: system
        pass_filenames: false
        always_run: true
        entry: poetry run python manage.py test
        stages: [push]