version: "3.7"

x-openwastemap: &app_image
  build:
    context: .
    target: applayer
  restart: "unless-stopped"
  env_file:
    - .env
  volumes:
    - ./owm/:/app/
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  app:
    <<: *app_image
    ports:
      - "127.0.0.1:7000:7000"
    command: python manage.py runserver 0.0.0.0:7000
  
  cmd:
    <<: *app_image
    restart: "no"
    command: python manage.py migrate --no-input
