# Generated by Django 3.2.9 on 2021-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owmuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
    ]
