"""Removed full_name from User model

Revision ID: 552c9b2db396
Revises: aecdb528222c
Create Date: 2022-11-23 10:51:29.467208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552c9b2db396'
down_revision = 'aecdb528222c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_full_name', table_name='user')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    # ### end Alembic commands ###
