"""Added table for tile cache.

Revision ID: 94ed19c44dd8
Revises: 552c9b2db396
Create Date: 2022-12-04 16:17:11.246012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ed19c44dd8'
down_revision = '552c9b2db396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cachedtile',
    sa.Column('zoom', sa.Integer(), nullable=False),
    sa.Column('xcoord', sa.Integer(), nullable=False),
    sa.Column('ycoord', sa.Integer(), nullable=False),
    sa.Column('change_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('zoom', 'xcoord', 'ycoord')
    )
    op.create_index(op.f('ix_cachedtile_xcoord'), 'cachedtile', ['xcoord'], unique=False)
    op.create_index(op.f('ix_cachedtile_ycoord'), 'cachedtile', ['ycoord'], unique=False)
    op.create_index(op.f('ix_cachedtile_zoom'), 'cachedtile', ['zoom'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cachedtile_zoom'), table_name='cachedtile')
    op.drop_index(op.f('ix_cachedtile_ycoord'), table_name='cachedtile')
    op.drop_index(op.f('ix_cachedtile_xcoord'), table_name='cachedtile')
    op.drop_table('cachedtile')
    # ### end Alembic commands ###
