"""added column last_refresh to for tile cache

Revision ID: f0b75973bb3a
Revises: 94ed19c44dd8
Create Date: 2022-12-07 12:33:34.966458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b75973bb3a'
down_revision = '94ed19c44dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cachedtile', sa.Column('last_refresh', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cachedtile', 'last_refresh')
    # ### end Alembic commands ###
