[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
uvicorn = "^0.18.3"
fastapi = "^0.85.0"
python-multipart = "^0.0.5"
email-validator = "^1.0.5"
requests = "^2.23.0"
celery = "^5.2.7"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
tenacity = "^8.0.1"
pydantic = "^1.4"
raven = "^6.10.0"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.8.5"
alembic = "^1.4.2"
sqlalchemy = "^1.3.16"
pytest = "^7.1.3"
python-jose = {extras = ["cryptography"], version = "^3.1.0"}
Pillow = "^9.1.0"
numpy = {version = "^1.22.3", python = ">=3.8,<3.11"}
Jinja2 = "^3.1.2"
fastapi-mail = "^1.1.4"

[tool.poetry.dev-dependencies]
mypy = "^0.770"
black = "^22.8"
isort = "^5.10.1"
autoflake = "^1.3.1"
flake8 = "^5.0.4"
pytest = "^7.1.3"
sqlalchemy-stubs = "^0.3"
pytest-cov = "^3.0.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

