[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Admin <admin@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
uvicorn = "^0.21.1"
fastapi = "^0.86.0"
python-multipart = "^0.0.6"
email-validator = "^1.3.1"
requests = "^2.28.2"
celery = "^5.2.7"
passlib = {extras = ["bcrypt"], version = "^1.7.2"}
tenacity = "^8.2.2"
pydantic = "^1.4"
raven = "^6.10.0"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.9.6"
alembic = "^1.10.1"
sqlalchemy = "^2.0.12"
pytest = "^7.2.0"
python-jose = {extras = ["cryptography"], version = "^3.1.0"}
Pillow = "^9.5.0"
numpy = {version = "^1.24.2", python = ">=3.8,<3.11"}
Jinja2 = "^3.1.2"
fastapi-mail = "^1.2.0"

[tool.poetry.dev-dependencies]
mypy = "^1.0"
black = "^22.10"
isort = "^5.10.1"
autoflake = "^1.7.1"
flake8 = "^5.0.4"
pytest = "^7.2.0"
sqlalchemy-stubs = "^0.4"
pytest-cov = "^4.0.0"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

