name: Backend CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Run test script
        env:
          CI_ENV_FILE: ${{ secrets.CI_ENV_FILE }}
        run: |
          echo $CI_ENV_FILE | base64 --decode > .env
          sh ./scripts/test.sh