name: Backend Build & Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
      - 'docker-compose*.yml'
  pull_request:
    branches:
      - master

jobs:
  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .env
        run: cp .github/build_and_test.env .env

      - uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Build Backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          target: backend
          push: false
          load: true
          tags: owm_backend
          cache-from: type=gha,scope=${{ github.workflow }}-backend
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-backend
          build-args: |
            INSTALL_DEV=true

      - name: Build Celeryworker
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/Dockerfile
          target: celeryworker
          push: false
          load: true
          tags: owm_celeryworker
          cache-from: type=gha,scope=${{ github.workflow }}-celeryworker
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-celeryworker
          build-args: |
            INSTALL_DEV=true

      - name: Run Setup
        env:
          TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL: false
        run: |
          docker-compose -f docker-compose.yml -f .github/docker-compose.ci.yml up -d --no-build db backend celeryworker queue

      - name: Test
        env:
          TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL: false
        run: |
          docker-compose -f docker-compose.yml -f .github/docker-compose.ci.yml exec -T backend bash /app/tests-start.sh "$@"
          docker-compose -f docker-compose.yml -f .github/docker-compose.ci.yml down -v
       
