name: Backend CI

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    #container: tiangolo/docker-with-compose
    steps:
      - name: Run test script
        run: ./scripts/test.sh
        shell: bash