name: Frontend Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - 'docker-compose*.yml'
  pull_request:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .env
        run: cp .github/build_and_test.env .env

      - uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Build Frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          load: true
          tags: owm_frontend
          cache-from: type=gha,scope=${{ github.workflow }}-frontend
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}-frontend
          build-args: |
            FRONTEND_ENV=dev

      - name: Run Setup
        env:
          TRAEFIK_PUBLIC_NETWORK_IS_EXTERNAL: false
        run: |
          docker compose -f docker-compose.yml up -d --no-build frontend
          docker compose -f docker-compose.yml down -v
